const Contactdetails = [
	{
		id: 0,
		image: "contimg/tech.png",
		title: "Event Management",
		team: [
			{
				name: "Garima Gaur",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "General Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Bhupesh Gaur",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "General Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 1,
		image: "contimg/tech.png",
		title: "Cultural",
		team: [
			{
				name: "Anish Singh",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Advisor To Cultural Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Kritika Bhardwaj",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Cultural Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Navya Kunwar",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Cultural Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Chirayu Gupta",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Cultural Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 2,
		image: "contimg/tech.png",
		title: "Creatives, Web & Tech",
		team: [
			{
				name: "Aadesh Agrawal (Web & Tech)",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Adviser To Technical Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Chaitanya Tyagi (Web & Tech)",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Technical Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Harsh Pratap Singh (Creatives)",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Technical Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Romil Modi (Creatives)",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Technical Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 3,
		image: "contimg/tech.png",
		title: "Mass & Media",
		team: [
			{
				name: "Chinmay Singh",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Mass & Media Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Kushagra Dutt",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Mass & Media Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 4,
		image: "contimg/tech.png",
		title: "Publicity",
		team: [
			{
				name: "Amol Kumar Urkude",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Publicity Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Abhishek Senger",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Publicity Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Soumya Jain",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Publicity Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 5,
		image: "contimg/tech.png",
		title: "Hospitality",
		team: [
			{
				name: "Harshvardhan Singh Rathore",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Vice President",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Poorvie Choudhary",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Vice President",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 6,
		image: "contimg/tech.png",
		title: "Logistics",
		team: [
			{
				name: "Shristi Gupta",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Logistics Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Rahul Kumar Dubey",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Logistics Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Harshit Khandelwal",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Logistics Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 7,
		image: "contimg/tech.png",
		title: "Marketing",
		team: [
			{
				name: "Divy Patil",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Marketing Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Deekshant Shah",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Marketing Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Satvik Pandey",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Marketing Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 8,
		image: "contimg/tech.png",
		title: "Decor",
		team: [
			{
				name: "Namra Khan ",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Decor Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Niteesh Kumar Jonnadula",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Decor Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Aman Agrawal",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Decor Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 9,
		image: "contimg/tech.png",
		title: "Finance",
		team: [
			{
				name: "Akshat Mantri",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Finance Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Pranav Dharmadikari",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Finance Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Lakshya Thakur",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Finance Secretary",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 10,
		image: "contimg/tech.png",
		title: "Security & Operations",
		team: [
			{
				name: "Abhishek Kumar Goutam",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "President",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
	{
		id: 11,
		image: "contimg/tech.png",
		title: "Overall coordinators",
		team: [
			{
				name: "Prateek Upadhyay",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Advisor to President",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
			{
				name: "Kshitij Singh Chandel",
				phone: 9798827707,
				email: "azad@gmail.com",
				position: "Advisor to Vice President",
				memimg: "contimg/Blitz_Logo_23.webp",
			},
		],
	},
];

export default Contactdetails;
