const Contactdetails = [
    {
        id: 1,
        image: 'contimg/tech.png',
        title: 'Technical Team',
        phone: '9798827707',
        teamsize: 3,
        email: 'azad@gmailblitzslag.com',
        name0: 'Azad Kumar',
        name1: 'kunal Kumar',
        name2: 'inviej Kumar',
        memimg0: 'contimg/azad.jpg',
        memimg1: 'contimg/azad.jpg',
        memimg2: 'contimg/azad.jpg',
        
    },
    {
        id: 2,
        image: 'contimg/tech.png',
        title: 'Logistic Team',
        phone: '9798827707',
        teamsize: 3,
        email: 'sega@gmailblitzslag.com',
        name0: 'Azad Kumar',
        name1: 'eoijk Kumar',
        name2: '3joiwj Kumar',
        memimg0: 'contimg/azad.jpg',
        memimg1: 'contimg/azad.jpg',
        memimg2: 'contimg/azad.jpg',
    },
    {
        id: 3,
        image: 'contimg/tech.png',
        title: 'Marketing Team',
        phone: '9798827707',
        teamsize: 3,
        email: 'pon@gmailblitzslag.com',
        name0: 'pokjfa Kumar',
        name1: 'djoaho Kumar',
        name2: 'dkpajek Kumar',
        memimg0: 'contimg/azad.jpg',
        memimg1: 'contimg/azad.jpg',
        memimg2: 'contimg/azad.jpg',
    },
    {
        id: 4,
        image: 'contimg/tech.png',
        title: 'Decoration Team',
        phone: '9798827707',
        teamsize: 3,
        email: 'prak@gmailblitzslag.com',
        name0: 'ieolmv Kumar',
        name1: 'ejp Kumar',
        name2: 'wpkkom Kumar',
        memimg0: 'contimg/azad.jpg',
        memimg1: 'contimg/azad.jpg',
        memimg2: 'contimg/azad.jpg',
    },
    {
        id: 5,
        image: 'contimg/tech.png',
        title: 'Technical Team',
        phone: '9798827707',
        teamsize: 3,
        email: 'devad@gmailblitzslag.com',
        name0: 'Azad Kumar',
        name1: 'kaljd Kumar',
        name2: 'dpaji Kumar',
        memimg0: 'contimg/azad.jpg',
        memimg1: 'contimg/azad.jpg',
        memimg2: 'contimg/azad.jpg',
    },
    {
        id: 6,
        image: 'contimg/tech.png',
        title: 'Technical Team',
        phone: '9798827707',
        teamsize: 3,
        email: 'chetan@gmailblitzslag.com',
        name0: 'ajkld Kumar',
        name1: 'andajo Kumar',
        name2: 'danpjn Kumar',
        memimg0: 'contimg/azad.jpg',
        memimg1: 'contimg/azad.jpg',
        memimg2: 'contimg/azad.jpg',
    },
    {
        id: 7,
        image: 'contimg/tech.png',
        title: 'Technical Team',
        phone: '9798827707',
        teamsize: 3,
        email: 'raju@gmailblitzslag.com',
        name0: 'alnlnd Kumar',
        name1: 'dnoaj Kumar',
        name2: ' dakl Kumar',
        memimg0: 'contimg/azad.jpg',
        memimg1: 'contimg/azad.jpg',
        memimg2: 'contimg/azad.jpg',
    },
]

export default Contactdetails