export default [
    {
        name:"abc",
        teamName:"xyz",
        nMembers:2,
        link:"#"
    },
    {
        name:"abc",
        teamName:"xyz",
        nMembers:2,
        link:"#"
    },
    {
        name:"abc",
        teamName:"xyz",
        nMembers:2,
        link:"#"
    },
    {
        name:"abc",
        teamName:"xyz",
        nMembers:2,
        link:"#"
    },
]